name: Cron Updater
on:
  # push:
  #   branch: [ master ]
  schedule:
    - cron: '5 * */1 * *'
  workflow_dispatch:
jobs:
  release:
    name: Cron Updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
           token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requests
        run: |
          pip install requests
      - name: Install YAML
        run: |
          pip install pyyaml    
      - name: Setting Up GitPush
        run: |
          git config user.email "yoboy907@gmail.com"
          git config user.name "Sabyasachi Seal"
        env:
          key: ${{ secrets.key }}
      - name: Update Cron
        run: |
          python cron.py
        env:
          key: ${{ secrets.key }}
      - name: Commit New YAML
        run: |
          git pull
          git add .
          git commit -m "CI: Update Cron"
