# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Master Workflow

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

      - name: Youtube Stats
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC5VBAKQWkYdrALsQ_W8woCg
          background_color: "#0d1117"
          title_color: "#39FF14"
          stats_color: "#dedede"
          commit_message: "(ci): Update YouTube cards"
          readme_path: README.md

      - name: Pull in community.aws and Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@yoboy907"
          feed_names: "Medium"
          template: "<tr><td>$title</td><td><a href=$url>$feedName</a></td><td>$categories</td></tr>$newline"
      
      - name: Feed the Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Sabyasachi-Seal
          outputs: |
            img/github-snake.svg?palette=github-dark&color_snake=orange
      
      - name: Getting Status
        run: git status

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: master
      #     force: true

      - name: Push Changes
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: ouput
          build_dir: img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name : Git Pull
      #   run: git pull
      
     # - name: Make GitArtwork SVG
     #   uses: jasineri/gitartwork@v1
     #   with:
     #     user_name: Sabyasachi-Seal
     #     text: Sabyasachi

      - name: Update Markdown Index
        run: |
          python docs/website.py

      - name: Git Status
        run: git status

      - name: Commit
        run: |
          git config user.name Sabyasachi Seal
          git config user.email yoboy907@gmail.com
          git add -A .
          git commit -m "Updated Data"
          git push

      # - name: PUSH
      #   uses: jasineri/simple-push-action@v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'profileviews'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BAEFC541DE0C400B82E7DE75229762E2 }}
          package: .
