name: Metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Main Workflow 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.ACTIONS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10

